### ISSUE TITLE
[DOC] - LICENSE has markdown issues

### ISSUE THREAD

**Issue by ieahleen** [naomis-novas/currency-bot#28]
### What is incorrect in the documentation?

The file LICENSE.md has various markdown issues making it pretty difficult to read, specifically sections 6 and 7

![image](https://github.com/naomis-novas/currency-bot/assets/26656284/750d89f5-7364-4df8-bb1d-9f41c63b5451)

### What should that text say?

Should be correctly formatted to be readable

**Comment by naomi-lgbt** [comment]
Resolved in https://github.com/naomis-novas/currency-bot/commit/eb911a37f637e705329c5f56ea552b36940465ae
